notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/bigbluebutton
    tag:
      - latest
      - 0.8.1-$${COMMIT:0:8}
    file: Dockerfile
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/bigbluebutton-proxy
    tag:
      - latest
    file: nginx/Dockerfile
    context: nginx
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  cache:
    mount:
      - docker/image.tar
